version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hello-there
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - main-network
    restart: unless-stopped


networks:
  main-network:
    driver: bridge

volumes:
  postgres: